### ISSUE TITLE
Error on dividers() method: copy.copy() broken

### ISSUE THREAD

**Issue by hasecilu** [instancezero/in3dca-freegrid#12]
I was giving a try to the workbench ([working btw](https://github.com/instancezero/in3dca-freegrid/tree/WorkBench)) when in the dividers part I get an error, decided to test the macro both the one from `main` branch and the one from #11  and all of them have the same error.

I don't know if something changed on `copy` or FreeCAD but the previous code doesn't work, I tried a lot of changes with the Part commands and `deepcopy` but nothing really worked, without the copies you only get the last horizontal/vertical dividers.

```python
16:12:35  Traceback (most recent call last):
16:12:35    File "/home/uli/.local/share/FreeCAD/Macro/in3dca_storage.FCMacro", line 349, in ok_button_click
16:12:35      self.start_button_click()
16:12:35    File "/home/uli/.local/share/FreeCAD/Macro/in3dca_storage.FCMacro", line 355, in start_button_click
16:12:35      self.generate_box()
16:12:35    File "/home/uli/.local/share/FreeCAD/Macro/in3dca_storage.FCMacro", line 319, in generate_box
16:12:35      Part.show(box.make(x, y, z, mag_d, mag_h), "In3D_" + size + "_box")
16:12:35                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:12:35    File "/home/uli/.local/share/FreeCAD/Macro/in3dca/StorageBox.py", line 603, in make
16:12:35      for divider in self.dividers():
16:12:35                     ^^^^^^^^^^^^^^^
16:12:35    File "/home/uli/.local/share/FreeCAD/Macro/in3dca/StorageBox.py", line 265, in dividers
16:12:35      dividers.append(copy.copy(divider))
16:12:35                      ^^^^^^^^^^^^^^^^^^
16:12:35    File "/usr/lib/python3.11/copy.py", line 92, in copy
16:12:35      rv = reductor(4)
16:12:35           ^^^^^^^^^^^
16:12:35  TypeError: cannot pickle 'Part.Solid' object
```

**Comment by instancezero** [comment]
That one is above my pay grade, and searching offers no helpful insights. I'd try asking on the FreeCAD forums; the issue might be deeper.

**Comment by hasecilu** [comment]
> That one is above my pay grade, and searching offers no helpful insights. I'd try asking on the FreeCAD forums; the issue might be deeper.

Probably it's the best option because I ran out of ideas, I even tried to fuse with the box inside divider() and that led to an other problems
