### ISSUE TITLE
Icons are ugly

### ISSUE THREAD

**Issue by hasecilu** [instancezero/in3dca-freegrid#19]
Current icons have big number of nodes and have sharpy edges.

**Comment by agryson** [comment]
I wrote the FreeCAD artwork guidelines back in FreeCAD 0.17 and did the refresh on all 1300+ icons back in that version.
I also did the Path workbench icons.
I could dust off my old templates and do a refresh/alignment of FreeGrid's ones as well if you like?

**Comment by instancezero** [comment]
I have no objection to that. @hasecilu has done most of the work of late, so I'd like to get his response too.

**Comment by agryson** [comment]
Of course, it's why I ask, if you look at my commits from back in the day I strived to keep the same design and only align colours/outlines to better adapt to light/dark schemes, align to pixel grid etc.
