### ISSUE TITLE
Created Box with Handle has volume stealing angle.

### ISSUE THREAD

**Issue by rhandel** [instancezero/in3dca-freegrid#6]
Was the box volume reduction intentional when creating a ledge for the label/grip?

**Comment by instancezero** [comment]
Hi @rhandel thanks for your input! It's required to avoid supports under the shelf. You can always generate with no label, then add your own shelf and print with supports. I'll add a "no wedge" option to the wish list but can't promise it will ever see production.

**Comment by rhandel** [comment]
I figured it was to eliminate supports.  I Was thinking the macro was deeper than the original one Zach used.  It looks like his angle is always 45 degrees.

**Comment by instancezero** [comment]
It's supposed to be 45 degrees. If it isn't, that's a bug!

**Comment by rhandel** [comment]
I'll check again.  I might be looking at it incorrectly.
