### ISSUE TITLE
Why no photos

### ISSUE THREAD

**Issue by buccaneer-jak** [instancezero/in3dca-freegrid#8]
A photo of the product might help, just saying. And Google didn't help.

**Comment by instancezero** [comment]
The product is a macro. There's a screen shot in the README file. Same file also contains several links to things like the website that hosts FreeGrid.

Also, not sure what you put into google but my search results differ.
![image](https://github.com/instancezero/in3dca-freegrid/assets/2599327/50744e92-9a1f-4709-9dc3-333c85ffa530)
